### ISSUE TITLE
Incoherent license

### ISSUE THREAD

**Issue by BaptisteGelez** [unixcorn-project/u_website#13]
This repo is under the CC-0 license, while the footer contains a CC-BY-NC-SA badge.

**Comment by myrdinm** [comment]
I like CC-0 but I don't have much knowledge about licences. What do you think ?

**Comment by m-blc** [comment]
I don't know much either about it, but I feel pretty OK with CC-0: https://choosealicense.com/licenses/cc0-1.0/

**Comment by BaptisteGelez** [comment]
Let's go for CC-0 then?

**Comment by myrdinm** [comment]
Ok for me.

**Comment by myrdinm** [comment]
Licence is now cc-0.
