### ISSUE TITLE
Some remarks regarding UI choices

### ISSUE THREAD

**Issue by m-blc** [unixcorn-project/u_website#20]
At our last physical meeting @rhaamo made some remarks and suggestions about our UI choices. In this issue I'll try to translate them into propositions.

### Header's height
The header (or navigation bar) use a lot of height space, here is how it looks on a standard HD screen:
![screen shot 2018-04-10 at 12 38 14](https://user-images.githubusercontent.com/10813340/38555042-ab167586-3cbc-11e8-8270-dc935f88cffa.png)
Maybe we can shrink it a little bit to regain some space?

### Homepage and scrolling
The whole homepage takes the entire size of a HD display, when you arrive you need to scroll down to find the first useful informations. See how it looks:
![screen shot 2018-04-10 at 12 38 23](https://user-images.githubusercontent.com/10813340/38555128-ef171c90-3cbc-11e8-9779-f00fea06b5e8.png)
Can we reduce the size of the logo? And in the same time the height of this space?

### Services section
Actually we can't see the whole services on an HD display, a bit of text and the buttons (link to the services) are missing, again you need to scroll down to find them.
![screen shot 2018-04-10 at 12 38 40](https://user-images.githubusercontent.com/10813340/38555229-4dfd0b70-3cbd-11e8-9923-041db5bfd479.png)
Can we reduce the space between the elements listed in this section?

### About more's section
Same problem here, there is a lot of blank space between this section and the other ones.
![screen shot 2018-04-10 at 12 38 50](https://user-images.githubusercontent.com/10813340/38555330-a3ded4a6-3cbd-11e8-8be6-f5307c1c9fd9.png)
Can we do the same as suggested previously?

### Support & contribution's panel
Again, same problem:
![screen shot 2018-04-10 at 12 39 06](https://user-images.githubusercontent.com/10813340/38555392-caaf89fe-3cbd-11e8-91b2-3c333e9971da.png)

Thanks in advance for helping here! @rhaamo don't hesitate to correct me if I'm wrong and/or add stuff I've forgot. 😄

**Comment by rhaamo** [comment]
IIRC that's what I said :+1:
